FROM ubuntu:focal

# User and group id
ARG UID=1000
ARG GID=1000

# Install packages
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y wget gnupg tzdata locales lsb-release apt-utils git

# Create postgres user/group with specific IDs
RUN groupadd -g $GID -o postgres
RUN useradd -m -u $UID -g $GID -o -s /bin/bash postgres

# Install PostgreSQL
RUN RELEASE_CODENAME=`lsb_release -c | awk '{print $2}'` && \
    echo 'deb http://apt.postgresql.org/pub/repos/apt/ '${RELEASE_CODENAME?}'-pgdg main' | \
        tee -a /etc/apt/sources.list.d/pgdg.list
RUN APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 && \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN apt-get update
RUN apt-get install -y make gcc libssl-dev libkrb5-dev
RUN apt-get install -y postgresql-9.5 postgresql-server-dev-9.5
RUN apt-get install -y postgresql-9.6 postgresql-server-dev-9.6
RUN apt-get install -y postgresql-10 postgresql-server-dev-10
RUN apt-get install -y postgresql-11 postgresql-server-dev-11
RUN apt-get install -y postgresql-12 postgresql-server-dev-12
RUN apt-get install -y postgresql-13 postgresql-server-dev-13
RUN apt-get install -y postgresql-14 postgresql-server-dev-14
RUN apt-get install -y postgresql-15 postgresql-server-dev-15

# Install Perl packages
RUN apt-get install -y libdbd-pg-perl libipc-system-simple-perl libterm-readkey-perl

# Build pgAudit
RUN git clone https://github.com/pgaudit/pgaudit.git -b REL9_5_STABLE /root/pgaudit/9.5
RUN make -C /root/pgaudit/9.5 install USE_PGXS=1 PG_CONFIG=/usr/lib/postgresql/9.5/bin/pg_config

RUN git clone https://github.com/pgaudit/pgaudit.git -b REL9_6_STABLE /root/pgaudit/9.6
RUN make -C /root/pgaudit/9.6 install USE_PGXS=1 PG_CONFIG=/usr/lib/postgresql/9.6/bin/pg_config

RUN git clone https://github.com/pgaudit/pgaudit.git -b REL_10_STABLE /root/pgaudit/10
RUN make -C /root/pgaudit/10 install USE_PGXS=1 PG_CONFIG=/usr/lib/postgresql/10/bin/pg_config

RUN git clone https://github.com/pgaudit/pgaudit.git -b REL_11_STABLE /root/pgaudit/11
RUN make -C /root/pgaudit/11 install USE_PGXS=1 PG_CONFIG=/usr/lib/postgresql/11/bin/pg_config

RUN git clone https://github.com/pgaudit/pgaudit.git -b REL_12_STABLE /root/pgaudit/12
RUN make -C /root/pgaudit/12 install USE_PGXS=1 PG_CONFIG=/usr/lib/postgresql/12/bin/pg_config

RUN git clone https://github.com/pgaudit/pgaudit.git -b REL_13_STABLE /root/pgaudit/13
RUN make -C /root/pgaudit/13 install USE_PGXS=1 PG_CONFIG=/usr/lib/postgresql/13/bin/pg_config

RUN git clone https://github.com/pgaudit/pgaudit.git -b REL_14_STABLE /root/pgaudit/14
RUN make -C /root/pgaudit/14 install USE_PGXS=1 PG_CONFIG=/usr/lib/postgresql/14/bin/pg_config

RUN git clone https://github.com/pgaudit/pgaudit.git -b REL_15_STABLE /root/pgaudit/15
RUN make -C /root/pgaudit/15 install USE_PGXS=1 PG_CONFIG=/usr/lib/postgresql/15/bin/pg_config

USER postgres
WORKDIR /var/lib/postgresql
