Vagrant.configure(2) do |config|
    config.vm.box = "bento/centos-7.3"

    config.vm.provider :virtualbox do |vb|
        vb.name = "pgaudit-analyze-centos7-test"
    end

    # Provision the VM
    config.vm.provision "shell", inline: <<-SHELL
        # Install PostgreSQL
        rpm -ivh http://yum.postgresql.org/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-3.noarch.rpm
        yum install -y postgresql95-server postgresql95-devel

        rpm -ivh http://yum.postgresql.org/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm
        yum install -y postgresql96-server postgresql96-devel

        rpm -ivh https://yum.postgresql.org/testing/10/redhat/rhel-7-x86_64/pgdg-centos10-10-1.noarch.rpm
        yum install -y postgresql10-server postgresql10-devel

        # Compile & install pgaudit
        yum install -y gcc openssl-devel git

        git clone https://github.com/pgaudit/pgaudit.git -b REL9_5_STABLE pgaudit-9.5
        bash -c 'export PATH="$PATH:/usr/pgsql-9.5/bin" && make -C pgaudit-9.5 install USE_PGXS=1'

        git clone https://github.com/pgaudit/pgaudit.git -b REL9_6_STABLE pgaudit-9.6
        bash -c 'export PATH="$PATH:/usr/pgsql-9.6/bin" && make -C pgaudit-9.6 install USE_PGXS=1'

        git clone https://github.com/pgaudit/pgaudit.git -b dev-pg10 pgaudit-10
        bash -c 'export PATH="$PATH:/usr/pgsql-10/bin" && make -C pgaudit-10 install USE_PGXS=1'

        # Install EPEL
        yum install -y epel-release

        # Install Perl
        yum install -y perl perl-DBD-Pg perl-IPC-System-Simple perl-TermReadKey
    SHELL

    # Don't share the default vagrant folder
    config.vm.synced_folder ".", "/vagrant", disabled: true

    # Mount project path for testing
    config.vm.synced_folder "..", "/pgaudit_analyze"
end
